import type { Metadata } from "next";
import { Raleway } from "next/font/google";
import "./globals.css";
import Header from "./components/Header";
import ThemeProviderWrapper from "./_theme/Providers/ThemeProviderWrapper";

const raleway = Raleway({ subsets: ["latin"], variable: "--font-raleway" });

export const metadata: Metadata = {
  title: "Fylo website",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${raleway.variable} font-sans`}>
        <ThemeProviderWrapper>
          <Header />
          <main>{children}</main>
        </ThemeProviderWrapper>
      </body>
    </html>
  );
}
